import type { Mod, FeaturedMod } from '@/types';

export const FEATURED_MODS: FeaturedMod[] = [
  {
    slug: 'purple-cat-girl-livery-annis-elegy-rh-7',
    title: 'Purple Cat Girl Livery - Annis Elegy RH-7 [4K Textures]',
    version: '1.0',
    author: 'Personka',
    coverImage: '/images/catgirl_1.jpg',
    thumbnailImage: '/images/catgirl_2.jpg',
    category: 'paintjobs',
  },
  {
    slug: 'betterchaseremade',
    title: 'BetterChaseRemade [Enhanced / Legacy]',
    version: '4.4.4-B',
    author: 'FlareXll',
    coverImage: '/images/5c9692-image.png',
    thumbnailImage: '/images/5c9692-image_1.png',
    category: 'scripts',
  },
  {
    slug: 'cessna-750-citation-x-add-on-sounds-legacy-enhanced',
    title: 'Cessna 750 Citation X [Add-On | Sounds | Legacy & Enhanced]',
    version: '1.0 LEGACY',
    author: 'Reacon',
    coverImage: '/images/1ba87e-4_1.jpg',
    thumbnailImage: '/images/1ba87e-4.jpg',
    category: 'vehicles',
  },
  {
    slug: 'mark-v-soc-add-on',
    title: 'Mark V SOC [Add-On]',
    version: '1.0',
    author: 'SkylineGTRFreak',
    coverImage: '/images/6ec60a-4_1.jpg',
    thumbnailImage: '/images/6ec60a-4.jpg',
    category: 'vehicles',
  },
  {
    slug: 'sukivehfuncsv-asi-legacy-enhanced',
    title: 'SukiVehFuncsV [ASI | Legacy | Enhanced]',
    version: '0.8.1',
    author: 'SukiHateProm1se',
    coverImage: '/images/7acc71-SukiVFV.png',
    thumbnailImage: '/images/7acc71-SukiVFV_1.png',
    category: 'scripts',
  },
  {
    slug: '2023-audi-rs6-avant-c8-abt',
    title: '2023 Audi RS6 Avant C8 ABT Legacy [HQ]',
    version: '2.0',
    author: 'MotorsportModding',
    coverImage: '/images/6252eb-bansh1.jpg',
    thumbnailImage: '/images/vehicles.jpg',
    category: 'vehicles',
  },
];

export const LATEST_MODS: Mod[] = [
  {
    id: 1,
    slug: 'personal-army-active-bodyguards-squads-and-teams-net-crash-fix',
    title: 'Personal Army (Active bodyguards squads and teams) [.NET] - Crash Fix',
    version: '1.1',
    category: 'scripts',
    subCategories: ['Gameplay', 'Vehicles', 'Player', 'Weapons', '.Net'],
    author: { username: 'chris22622' },
    stats: { downloads: 21, likes: 1, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/f1e862-hero_upload.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 2,
    slug: 'quicksilver-net-crash-fix',
    title: 'Quicksilver [.NET] - Crash Fix',
    version: '1.1',
    category: 'scripts',
    subCategories: ['Gameplay', 'Player', '.Net'],
    author: { username: 'chris22622' },
    stats: { downloads: 6, likes: 0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/b644a7-hero.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 3,
    slug: 'injured-peds',
    title: 'Injured Peds',
    version: '1.0',
    category: 'scripts',
    subCategories: ['Gameplay', '.Net'],
    author: { username: 'ww_aleeex' },
    stats: { downloads: 176, likes: 3, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/04711c-2312312414.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 4,
    slug: 'banshee-gts-custom-add-on-tuning-template',
    title: 'Banshee GTS Custom [Add-On | Tuning | Template]',
    version: '1.0',
    category: 'vehicles',
    subCategories: ['Add-On', 'Car', 'Lore Friendly', 'Vanilla Edit', 'Tuning', 'Template'],
    author: { username: 'Silentm503' },
    stats: { downloads: 149, likes: 10, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/6252eb-bansh1.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 5,
    slug: 'shadowrun-loading-music',
    title: 'Shadowrun Loading Music',
    version: '1.0',
    category: 'misc',
    subCategories: ['Loading'],
    author: { username: 'InfiniteQuestion' },
    stats: { downloads: 0, likes: 0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/c085f7-4.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 6,
    slug: 'dynamic-ped-health',
    title: 'Dynamic Ped Health',
    version: '1.0',
    category: 'scripts',
    subCategories: ['Gameplay', '.Net'],
    author: { username: 'ww_aleeex' },
    stats: { downloads: 154, likes: 6, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/c0bfe4-Untitlededdd-111.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 7,
    slug: 'purple-cat-girl-livery-annis-elegy-rh-7',
    title: 'Purple Cat Girl Livery for Annis Elegy RH-7',
    version: '1.0',
    category: 'paintjobs',
    subCategories: ['Livery'],
    author: { username: 'Personka' },
    stats: { downloads: 0, likes: 0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/e24e7a-3.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 8,
    slug: 'mig-29-ukrainian-air-force-beaver-04-114th-tactical-aviation-brigade-livery',
    title: 'mig-29 ukrainian air force - beaver (04) - 114th tactical aviation brigade (livery)',
    version: '1.0',
    category: 'paintjobs',
    subCategories: ['Livery', 'Europe'],
    author: { username: 'xavgoinxrazy' },
    stats: { downloads: 7, likes: 0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/8f89e5-png4.png',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
];

export const MOST_LIKED_MODS: Mod[] = [
  {
    id: 9,
    slug: 'los-santos-drug-wars-in-sp',
    title: 'Los Santos Drug Wars in SP',
    version: '1.0',
    category: 'scripts',
    subCategories: ['Mission', 'Gameplay', '.Net'],
    author: { username: 'HKH191' },
    stats: { downloads: 605, likes: 31, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/6974c3-LosSantosDrugWarsInSP.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 10,
    slug: 'realistic-reverse-backup-camera-dynamic-park-assist',
    title: 'Realistic Reverse Backup Camera & Dynamic Park Assist',
    version: '1.1.0',
    category: 'scripts',
    subCategories: ['Gameplay', 'Vehicles', '.Net'],
    author: { username: 'lelelelelelele' },
    stats: { downloads: 487, likes: 23, rating: 4.7, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/2a6b6a-preview_1.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 11,
    slug: 'bugatti-centodieci-add-on-legacy-enhanced',
    title: 'Bugatti Centodieci [Add-On | Legacy | Enhanced]',
    version: '1.0',
    category: 'vehicles',
    subCategories: ['Add-On', 'Car', 'Bugatti', 'Enhanced'],
    author: { username: 'Hammer76' },
    stats: { downloads: 1258, likes: 18, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/0f1edd-1.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 12,
    slug: 'bums-interactions',
    title: 'Bums interactions',
    version: '1.0',
    category: 'scripts',
    subCategories: ['Gameplay', '.Net'],
    author: { username: 'thalilmythos' },
    stats: { downloads: 278, likes: 18, rating: 4.86, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/605ee4-bumm.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 13,
    slug: 'honda-nsx-gt500-2023-add-on',
    title: 'Honda NSX GT500 2023 [Add-On | Legacy | Enhanced]',
    version: '1.1',
    category: 'vehicles',
    subCategories: ['Add-On', 'Honda', 'Car'],
    author: { username: 'HappyEndgr' },
    stats: { downloads: 1032, likes: 17, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/0cb306-A.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 14,
    slug: 'bmw-m4-dtm-2020',
    title: 'BMW M4 DTM 2020 [Add-On]',
    version: '1.0',
    category: 'vehicles',
    subCategories: ['Car', 'Bmw', 'Add-On'],
    author: { username: 'HappyEndgr' },
    stats: { downloads: 763, likes: 16, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/05922d-2.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 15,
    slug: 'rapper-v',
    title: 'Rapper V',
    version: '1.0.0',
    category: 'scripts',
    subCategories: ['Gameplay', 'Player', '.Net'],
    author: { username: 'JayJayAydens' },
    stats: { downloads: 344, likes: 16, rating: 5.0, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/2e6a83-image.jpg',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
  {
    id: 16,
    slug: 'mercedes-benz-amg-gt3-evo-add-on-fivem-tuning-template',
    title: 'Mercedes-Benz AMG GT3 EVO [Add-On / FiveM / Tuning / Template]',
    version: 'v1.0',
    category: 'vehicles',
    subCategories: ['Add-On', 'Car', 'Wheels', 'Handling', 'Mercedes-Benz', 'Tuning', 'Template'],
    author: { username: 'Songuo' },
    stats: { downloads: 789, likes: 14, rating: 4.7, commentsCount: 0 },
    tags: [],
    description: '',
    coverImage: '/images/0bfd30-1.png',
    thumbnailImages: [],
    allVersions: [],
    firstUploadedAt: '',
    lastUpdatedAt: '',
  },
];

export const PRODUCT_DETAIL_MOD: Mod = {
  id: 288771,
  slug: 'purple-cat-girl-livery-annis-elegy-rh-7',
  title: 'Purple Cat Girl Livery for Annis Elegy RH-7',
  version: '1.0',
  category: 'paintjobs',
  subCategories: ['Livery'],
  author: {
    username: 'Personka',
    avatarUrl: '/images/e20583-d72ad9b02d18582b0b4a72b5ccf9be9a.jpg',
    discordUrl: 'https://discord.gg/mJYAame3jv',
  },
  stats: { downloads: 0, likes: 0, rating: 0, commentsCount: 0 },
  tags: [{ name: 'Livery', slug: 'livery' }],
  description:
    "Hello everyone!!<br>I'm Personka and I'm beginner graphic designner.<br>If you like this livery I would be gratefull if you joined my discord server!!&lt;3<br>https://discord.gg/6ZWwPNvawS<br><br>──────────────────────────────────────────────────────<br>INSTALLATION <br>1. Replace the original carcols.meta with attached file in the meta folder.<br>2. Put the rh7_liv_59.yft file in the stream folder.<br>──────────────────────────────────────────────────────",
  coverImage: '/images/e24e7a-3_1.jpg',
  thumbnailImages: [
    '/images/e24e7a-5.jpg',
    '/images/e24e7a-2.jpg',
    '/images/e24e7a-1.jpg',
    '/images/e24e7a-4.jpg',
    '/images/e24e7a-6.jpg',
    '/images/e24e7a-7.jpg',
  ],
  allVersions: [
    {
      version: '1.0',
      isCurrent: true,
      downloads: 0,
      fileSize: '6.58 MB',
      uploadedAt: '12 hours ago',
      downloadUrl: '/paintjobs/purple-cat-girl-livery-annis-elegy-rh-7/download/200229',
      virusTotalUrl:
        'https://www.virustotal.com/gui/file/b809669bbafb3ae0a0eff06e88d3368f36c2970316fb71a74322b2425653b893/detection/f-b809669bbafb3ae0a0eff06e88d3368f36c2970316fb71a74322b2425653b893-1787250317',
      virusTotalHash: 'b809669bbafb3ae0a0eff06e88d3368f36c2970316fb71a74322b2425653b893',
    },
  ],
  firstUploadedAt: 'Thu, 20 Aug 2026 18:23:13 +0000',
  lastUpdatedAt: 'Fri, 21 Aug 2026 05:29:36 +0000',
};
